apiVersion: apps/v1
kind: Deployment
metadata:
  name: presence-service
  labels:
    app: presence-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presence-service
  template:
    metadata:
      labels:
        app: presence-service
    spec:
      containers:
        - name: presence-service
          imagePullPolicy: IfNotPresent
          image: nats-chat/presence-service:latest
          env:
            - name: NATS_URL
              value: nats://nats:4222
            - name: NATS_USER
              value: presence-service
            - name: NATS_PASS
              value: presence-service-secret
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_SERVICE_NAME
              value: presence-service
