apiVersion: apps/v1
kind: Deployment
metadata:
  name: translation-service
  labels:
    app: translation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation-service
  template:
    metadata:
      labels:
        app: translation-service
    spec:
      containers:
        - name: translation-service
          imagePullPolicy: IfNotPresent
          image: nats-chat/translation-service:latest
          env:
            - name: NATS_URL
              value: nats://nats:4222
            - name: NATS_USER
              value: translation-service
            - name: NATS_PASS
              value: translation-service-secret
            - name: OLLAMA_URL
              value: http://ollama:11434
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_SERVICE_NAME
              value: translation-service
