apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nats-chat

resources:
  - ../../base
  - ingress.yaml
  - secrets.yaml
  - grafana-nodeport.yaml

patches:
  - path: patches/web-env.yaml
  - path: patches/keycloak-env.yaml
  - path: patches/keycloak-proxy.yaml
  - path: patches/sticker-env.yaml
  - path: patches/postgres-init-env.yaml
  - path: patches/translation-env.yaml
  - path: patches/grafana-env.yaml
