apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  POSTGRES_USER: chat
  POSTGRES_PASSWORD: chat-secret
  DATABASE_URL: postgres://chat:chat-secret@postgres:5432/chatdb?sslmode=disable
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-nkeys
type: Opaque
stringData:
  ISSUER_NKEY_SEED: SAANDLKMXL6CUS3CP52WIXBEDN6YJ545GDKC65U5JZPPV6WH6ESWUA6YAI
  XKEY_SEED: SXAAXMRAEP6JWWHNB6IKFL554IE6LZVT6EY5MBRICPILTLOPHAG73I3YX4
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
type: Opaque
stringData:
  KEYCLOAK_ADMIN_USER: admin
  KEYCLOAK_ADMIN_PASS: admin
