apiVersion: v1
kind: Service
metadata:
  name: sticker-images
  labels:
    app: sticker-images
spec:
  type: ClusterIP
  selector:
    app: sticker-images
  ports:
    - name: http
      port: 8090
      targetPort: 8090
