apiVersion: v1
kind: ConfigMap
metadata:
  name: web-env
data:
  env.js: |
    window.__env__ = {
      VITE_KEYCLOAK_URL: "https://chat.cowbay.wtf/auth",
      VITE_KEYCLOAK_REALM: "nats-chat",
      VITE_KEYCLOAK_CLIENT_ID: "nats-chat-app",
      VITE_NATS_WS_URL: "wss://chat.cowbay.wtf/nats-ws"
    };
