apiVersion: v1
kind: Service
metadata:
  name: poll-app
  labels:
    app: poll-app
spec:
  type: ClusterIP
  selector:
    app: poll-app
  ports:
    - name: http
      port: 8091
      targetPort: 8091
