apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-app
  labels:
    app: whiteboard-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whiteboard-app
  template:
    metadata:
      labels:
        app: whiteboard-app
    spec:
      containers:
        - name: whiteboard-app
          imagePullPolicy: IfNotPresent
          image: nats-chat/whiteboard-app:latest
          ports:
            - containerPort: 8092
              name: http
